#!/bin/bash

set -e
set -u
set -o pipefail

detectOSPlatform() {
	OSNAME=$(uname)

	if [[ "${OSNAME}" = "Darwin" ]]; then
	 	OSNAME=macos
	elif [[ "${OSNAME}" = "Linux" ]]; then
		OSNAME=linux
	fi

	echo ${OSNAME}
}

SCRIPT_CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

METERIAN_HOME_DIR=${HOME}/.meterian

PATH="${METERIAN_HOME_DIR}:${PATH}"                                   \
    "${SCRIPT_CURRENT_DIR}/meterian-cli-$(detectOSPlatform)"          \
            -Djava.library.path="${METERIAN_HOME_DIR}"                \
            -Djavax.net.ssl.trustStore="${METERIAN_HOME_DIR}/cacerts" \
            -Djavax.net.ssl.trustStorePassword=changeit               \
            $*